// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/codeEditor/codeEditor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Menu: typeof import('./src/components/nav/component/navLeft/menu.vue')['default']
    Nav: typeof import('./src/components/nav/nav.vue')['default']
    NavLeft: typeof import('./src/components/nav/component/navLeft/navLeft.vue')['default']
    NavTop: typeof import('./src/components/nav/component/navTop/navTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/set/set.vue')['default']
    Svg: typeof import('./src/components/svg/svg.vue')['default']
    Uploading: typeof import('./src/components/uploading/uploading.vue')['default']
    View: typeof import('./src/components/view/view.vue')['default']
  }
}

export {}
